# -*- coding: utf-8 -*-
import message

DEFAULT_TAG_ID = 1 #文章默认显示的标签

#角色类别id
ROLE_NORMAL_ID = 1 	#普通会员
ROLE_NORMAL_NAME = u'普通会员'
ROLE_VIP_ID = 2		#普通VIP
ROLE_VIP_NAME = u'VIP会员'
ROLE_SUPER_VIP_ID = 3	#超级VIP
ROLE_SUPER_VIP_NAME = u'高级VIP会员'

DAY_ALERT = 30 	#提示时间，30天以内提示
DAY_SINGLE = 3 	#点播，1天有效时间
DAY_MEMBER = 365	#会员，365天

#用户阅读权限分配
PERMISSION_MEMBER_USER_NORMAL_2_ARTICLE_NORMAL= '3001'
PERMISSION_MEMBER_USER_NORMAL_2_ARTICLE_VIP = '3002'
PERMISSION_MEMBER_USER_NORMAL_2_ARTICLE_SUPER_VIP = '3003'
PERMISSION_MEMBER_USER_VIP_2_ARTICLE_NORMAL = '3004'
PERMISSION_MEMBER_USER_VIP_2_ARTICLE_VIP = '3005'
PERMISSION_MEMBER_USER_VIP_2_ARTICLE_SUPER_VIP = '3006'
PERMISSION_MEMBER_USER_SUPER_VIP_2_ARTICLE_NORMAL = '3007'
PERMISSION_MEMBER_USER_SUPER_VIP_2_ARTICLE_VIP = '3008'
PERMISSION_MEMBER_USER_SUPER_VIP_2_ARTICLE_SUPER_VIP = '3009'
PERMISSION_SINGLE_NORMAL = '4001'
PERMISSION_SINGLE_NEVER = '4002'
PERMISSION_SINGLE_TIMEOUT = '4003'

#支付模式
PAY_SINGLE_VIP = '5001'
PAY_SINGLE_SUPER_VIP = '5002'
PAY_MEMBER_VIP = '5003'
PAY_MEMBER_SUPER_VIP = '5004'
#支付金额
PAY_PRICE_20 = '20'
PAY_PRICE_30 = '30'
PAY_PRICE_800 = '800'
PAY_PRICE_3500 = '3500'


#用户认证状态
USER_CHECK_NEVER = 0  	#未提交
USER_CHECK_APPLY = 1	#已提交
USER_CHECK_REFUSE = 2	#审核不通过
USER_CHECK_PASS = 3		#审核通过







def GetUtil():
	return {
		'DEFAULT_TAG_ID': DEFAULT_TAG_ID, #文章默认显示的标签

		#角色类别id
		'ROLE_NORMAL_ID': ROLE_NORMAL_ID ,	#普通会员
		'ROLE_VIP_ID': ROLE_VIP_ID,		#普通VIP
		'ROLE_SUPER_VIP_ID'	: ROLE_SUPER_VIP_ID,	#超级VIP
	 	'ROLE_NORMAL_NAME': ROLE_NORMAL_NAME,
       	'ROLE_VIP_NAME':ROLE_VIP_NAME,
        'ROLE_SUPER_VIP_NAME': ROLE_SUPER_VIP_NAME,
		'DAY_SINGLE' : DAY_SINGLE,	#点播，1天有效时间
		'DAY_MEMBER' : DAY_MEMBER,	#会员，365天

		#用户阅读权限分配
		'PERMISSION_MEMBER_USER_NORMAL_2_ARTICLE_NORMAL' :PERMISSION_MEMBER_USER_NORMAL_2_ARTICLE_NORMAL,
		'PERMISSION_MEMBER_USER_NORMAL_2_ARTICLE_VIP' :PERMISSION_MEMBER_USER_NORMAL_2_ARTICLE_VIP,
		'PERMISSION_MEMBER_USER_NORMAL_2_ARTICLE_SUPER_VIP' :PERMISSION_MEMBER_USER_NORMAL_2_ARTICLE_SUPER_VIP,
		'PERMISSION_MEMBER_USER_VIP_2_ARTICLE_NORMAL' :PERMISSION_MEMBER_USER_VIP_2_ARTICLE_NORMAL,
		'PERMISSION_MEMBER_USER_VIP_2_ARTICLE_VIP' : PERMISSION_MEMBER_USER_VIP_2_ARTICLE_VIP,
		'PERMISSION_MEMBER_USER_VIP_2_ARTICLE_SUPER_VIP' : PERMISSION_MEMBER_USER_VIP_2_ARTICLE_SUPER_VIP,
		'PERMISSION_MEMBER_USER_SUPER_VIP_2_ARTICLE_NORMAL' : PERMISSION_MEMBER_USER_SUPER_VIP_2_ARTICLE_NORMAL,
		'PERMISSION_MEMBER_USER_SUPER_VIP_2_ARTICLE_VIP' : PERMISSION_MEMBER_USER_SUPER_VIP_2_ARTICLE_VIP,
		'PERMISSION_MEMBER_USER_SUPER_VIP_2_ARTICLE_SUPER_VIP' : PERMISSION_MEMBER_USER_SUPER_VIP_2_ARTICLE_SUPER_VIP,
		'PERMISSION_SINGLE_NORMAL' : PERMISSION_SINGLE_NORMAL,
		'PERMISSION_SINGLE_NEVER' : PERMISSION_SINGLE_NEVER,
		'PERMISSION_SINGLE_TIMEOUT' : PERMISSION_SINGLE_TIMEOUT,

		#支付模式
		'PAY_SINGLE_VIP' : PAY_SINGLE_VIP,
		'PAY_SINGLE_SUPER_VIP' : PAY_SINGLE_SUPER_VIP,
		'PAY_MEMBER_VIP' : PAY_MEMBER_VIP,
		'PAY_MEMBER_SUPER_VIP' : PAY_MEMBER_SUPER_VIP,
		#支付金额
		'PAY_PRICE_20' : PAY_PRICE_20,
		'PAY_PRICE_30' : PAY_PRICE_30,
		'PAY_PRICE_800' : PAY_PRICE_800,
		'PAY_PRICE_3500' : PAY_PRICE_3500,
	}



#model 通用
IS_PAYMENT_FALSE = 0 #待支付
IS_PAYMENT_TRUE = 1  #已支付


AGREEMENT_TYPE_MEMBER = 0
AGREEMENT_TYPE_SINGLE_TIME = 1
AGREEMENT_TYPE_SINGLE_NUMBER = 2


DISCOUNT_IS_USED_FALSE = 0 #优惠券未使用
DISCOUNT_IS_USED_TRUE = 1 #优惠券已使用

SELF = 2
YES = 1
NO = 0

PAGE_NUM = 0 #初始化从第0页开始搜索
PAGE_SIZE = 6
PAGE_SEARCH_SIZE = 20

# READ_MODE_IS_FREE = True
READ_MODE_IS_FREE = False

ADMIN_PER_PAGE = 20


# DISCOUNT_STYLE_MEMBER = 0 #会员打折券
# DISCOUNT_STYLE_SINGLE_TIME = 1 #限时点播券
# DISCOUNT_STYLE_SINGLE_NUMBER = 2 #按次点播券


TAG_MEET = 16 #会议，默认标签
TAG_BANNER = 19 #广告
TAG_SWIPER = 20 #滚动栏，默认标签

#角色等级
ROLE_LEVEL_1 = 1
ROLE_LEVEL_2 = 2
ROLE_LEVEL_3 = 3



MEET_SWIPER_AGENDA = 1
MEET_SWIPER_NEWS = 2
MEET_SWIPER_SPONSOR = 3
MEET_SWIPER_STYLE = {
	MEET_SWIPER_AGENDA:"日程",
	MEET_SWIPER_NEWS:"新闻",
	# MEET_SWIPER_SPONSOR:"赞助商",
}


MEET_MAIN = 1
MEET_AGENDA = 2
MEET_SPOT = 3
MEET_STYLE = {
	MEET_MAIN : "主会议",
	MEET_AGENDA:"日程",
	MEET_SPOT:"分会场",
}



