# -*- coding: utf-8 -*-
"""
Django settings for huaxun_server project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!h*51f3vo17s0d+71khv&^siolw_=ogf*e6$xtj-lp(g_-#u9+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# ENV_TEST = True #微信支付测试环境
ENV_TEST = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'order',
    'match',
    'roster',
    'log',
    'meet',
    'meet_sign',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', 
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'api.lib.middleware.SessionMiddleware'
)

ROOT_URLCONF = 'huaxun_server.urls'

#django suit
from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS as TCP
TEMPLATE_CONTEXT_PROCESSORS = TCP + (
    'django.core.context_processors.request',
)
SUIT_CONFIG = {
    # header
    'ADMIN_NAME': u'华讯生物圈小程序管理系统',
    'HEADER_DATE_FORMAT': 'l, j. F Y', # Saturday, 16th March 2013
    'HEADER_TIME_FORMAT': 'H:i',       # 18:42

     # forms
    'SHOW_REQUIRED_ASTERISK': True, #Automatically adds asterisk symbol * to the end of every required field label:
    'CONFIRM_UNSAVED_CHANGES': True, #Alert will be shown, when you’ll try to leave page, without saving changed form first:

     # menu
    'SEARCH_URL': '/huaxun/admin/api/user/',
    'MENU_ICONS': {
        'sites': 'icon-leaf',
        'auth': 'icon-lock',
    },
     'MENU_EXCLUDE': ('auth.group', 'auth'),#  menu不显示的栏目图标
    # 'MENU': (
    #     # sites是默认原先的app和models
    #     # 'sites',
    #     '-',
    #     {'app': 'api', 'label': u'小程序', 'icon': 'icon-lock',
    #     #   'models': (
    #     #     'meet.ImageLibrary',
    #     #     'meet.ArticleStyle',
    #     #     'meet_sign.Attendee',
		# #
    #     # )
    #      },
    #     # '-',
    #     # {'app': 'duser', 'label': u'平台用户', 'icon': 'icon-user'},
    #     # '-',
    #     # {'app': 'dtheme', 'label': u'主题管理', 'icon': 'icon-tags'},
    #     # '-',
    #     # {'app': 'dpost', 'label': u'文章管理', 'icon': 'icon-edit'},
    #     # '-',
    #     # # 如果使用http这种绝对路径的话，菜单不会展开，且不会标记为active状态
    #     # {'url': '/admin/theme/mysql', 'label': u'第三数据', 'icon': 'icon-lock'},
    #     '-',
    #     {'label': u'统计数据231432', 'icon': 'icon-tags',
    #      'models': (
    #         'meet.ImageLibrary',
    #         'meet.ArticleStyle',
    #         'meet_sign.Attendee',
	#
    #     )}
    # ),
    # misc
    'LIST_PER_PAGE': 15
}



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'huaxun_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    # 'default': {
    #    'ENGINE': 'django.db.backends.sqlite3',
    #    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hua_xun',
        'USER': 'root',
        'PASSWORD':'root',
        'HOST':'127.0.0.1',
        'PORT':'3306',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh_CN'
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True

USE_L10N = True

# USE_TZ = True
USE_TZ = False #计算机所在地时间#

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

HOST_URL = 'huaxun_2'
#STATIC_URL =  '/' + HOST_URL + '/static/'# 本地测试
STATIC_URL = '/huaxun/static/' #  HTTPS 运营环境
STATIC_ROOT = os.path.join(BASE_DIR, "static") #pythonanywhere use

MEDIA_URL=  '/' + HOST_URL + '/static/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media") #pythonanywhere use

# MEDIA_URL='/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, "media") #pythonanywhere use
# print 'MEDIA_ROOT',MEDIA_ROOT
FILE_CHARSET = 'gb18030'
# FILE_CHARSET = 'gbk'
# FILE_CHARSET = 'utf-8'
DEFAULT_CHARSET = 'utf-8'

# log配置
# LOG_FILE = "./all.log"
#
# LOGGING = {
#         'version': 1,
#         'disable_existing_loggers': True,
#
#         'filters': {
#             'require_debug_false': {
#                 '()': 'django.utils.log.RequireDebugFalse'
#                 }
#             },
#         'formatters': {
#             'simple': {
#                 'format': '[%(levelname)s] %(module)s : %(message)s'
#                 },
#             'verbose': {
#                 'format':
#                     '[%(asctime)s] [%(levelname)s] %(module)s : %(message)s'
#                 }
#             },
#
#         'handlers': {
#             'null': {
#                 'level': 'DEBUG',
#                 'class': 'django.utils.log.NullHandler',
#                 },
#             'console': {
#                 'level': 'INFO',
#                 'class': 'logging.StreamHandler',
#                 'formatter': 'verbose'
#                 },
#             'file': {
#                 'level': 'INFO',
#                 'class': 'logging.FileHandler',
#                 'formatter': 'verbose',
#                 'filename': LOG_FILE,
#                 'mode': 'a',
#                 },
#             'mail_admins': {
#                 'level': 'ERROR',
#                 'class': 'django.utils.log.AdminEmailHandler',
#                 'filters': ['require_debug_false']
#                 }
#             },
#         'loggers': {
#             'django': {
#                 'handlers': ['file', 'console'],
#                 'level': 'DEBUG',
#                 'propagate': True,
#             },
#              'django.request': {
#                 'handlers': ['mail_admins', 'console'],
#                 'level': 'ERROR',
#                 'propagate': True,
#             },
#         }
# }

#华讯
APP_ID = "wx51930c31391cc5cc"
APP_SECRET = "0004ddafadf09d541dadee17a533b60f"
MACH_ID = "1488713872"
MACH_KEY = "283fc3d9d4b8ba3b58601145466d4417"
PAY_CALLBACK_URL = "https://xcx.308308.com/huaxun_2/api/pay/callback/wx/"
PAY_RENEW_CALLBACK_URL = "https://xcx.308308.com/huaxun_2/api/pay/callback/wx_renew/"
# 表情袋
# APP_ID = "wxff79e25befbb413d"
# APP_SECRET = "283fc3d9d4b8ba3b58601145466d4417"
# MACH_ID = "1480337772"
# MACH_KEY = "283fc3d9d4b8ba3b58601145466d4417"
   # '': {
   #              'handlers': ['file', 'console'],
   #              'level': 'INFO',
   #              'propagate': True,
   #          },

# 七牛配置
##qiniu_access_key = 'bK5xWj0a-TBIljlxHYOHuQib9HYF_9Ft-HtP8tEb'
##qiniu_secret_key = '56lucORYc45sF5eDqNk63mLXsQ78n4RrubIrjtE0'
##qiniu_bucket_name = 'clickz'

qiniu_access_key = 'WVtzKqUQo0dqEVIB68xmajLqtgI_m0XILdll7-ms'
qiniu_secret_key = 'qXuv5WQfIqDrqKBdPu-9BgR531BYwEoQhOnNGPF6'
qiniu_bucket_name = 'huaxun'

